include_guard(GLOBAL)
include(${PROJECT_SOURCE_DIR}/cmake/colorful.cmake)

set(DENOX_ABSL_COMPONENTS "strings;cord;log;check"
    CACHE STRING "Abseil components to link")

# 1) Prefer the official CMake config package (most distros/vcpkg/conan)
find_package(absl CONFIG QUIET)

if (absl_FOUND)
  set(_absl_targets)
  foreach(_c IN LISTS DENOX_ABSL_COMPONENTS)
    if (TARGET "absl::${_c}")
      list(APPEND _absl_targets "absl::${_c}")
    else()
      log_error("absl component not found in config package: absl::${_c}")
    endif()
  endforeach()

  if (_absl_targets)
    add_library(denox::absl INTERFACE IMPORTED)
    target_link_libraries(denox::absl INTERFACE ${_absl_targets})
    list(JOIN DENOX_ABSL_COMPONENTS ", " _comp_list)
    log_success("✅ absl available (config): ${_comp_list}")
    return()
  endif()
endif()

find_path(ABSL_INCLUDE_DIR NAMES absl/strings/string_view.h)

set(_absl_libs)
set(_missing OFF)
foreach(_c IN LISTS DENOX_ABSL_COMPONENTS)
  set(_libname "absl_${_c}")
  find_library(_lib_${_libname} NAMES ${_libname})
  if (_lib_${_libname})
    list(APPEND _absl_libs "${_lib_${_libname}}")
  else()
    set(_missing ON)
    log_error("Missing absl library: ${_libname}")
  endif()
endforeach()

if (NOT _missing AND _absl_libs)
  add_library(denox::absl INTERFACE IMPORTED)
  if (ABSL_INCLUDE_DIR)
    target_include_directories(denox::absl INTERFACE "${ABSL_INCLUDE_DIR}")
  endif()
  target_link_libraries(denox::absl INTERFACE ${_absl_libs})
  list(JOIN DENOX_ABSL_COMPONENTS ", " _comp_list)
  log_success("✅ absl available (manual libs): ${_comp_list}")
  return()
endif()

log_error("❌ absl not found. Install abseil-cpp (CMake config preferred).")
