include_guard(GLOBAL)

set(PNG_SHARED OFF CACHE BOOL "" FORCE)
set(PNG_STATIC ON CACHE BOOL "" FORCE)
set(PNG_FRAMEWORK OFF CACHE BOOL "" FORCE)
set(PNG_TESTS OFF CACHE BOOL "" FORCE)
set(PNG_TOOLS OFF CACHE BOOL "" FORCE)
set(PNG_HARDWARE_OPTIMIZATIONS OFF CACHE BOOL "" FORCE)

FetchContent_Declare(
  png
  GIT_REPOSITORY https://github.com/pnggroup/libpng.git
  GIT_TAG c3e304954a9cfd154bc0dfbfea2b01cd61d6546d # v1.6.55
  GIT_SHALLOW TRUE
  OVERRIDE_FIND_PACKAGE
  GIT_PROGRESS TRUE
  EXCLUDE_FROM_ALL
)
FetchContent_MakeAvailable(png)

set_target_properties(png_static PROPERTIES UNITY_BUILD OFF)




